[package]
name = "tlsecho"
version = "0.1.0"
authors = ["Vincent Foley <vfoley@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version="~2.32.0", default-features=false }
rustls = "~0.15.0"
webpki = "~0.19.0"
log = "0.4"
env_logger = "0.6"
